****Scikit-learn****

In [1]:
import pandas as pd
import yfinance as yf
import numpy as np
from datetime import date

In [2]:
ticker = 'MSFT'
start_date = '2020-01-01'
end_date = '2025-12-31'

df = yf.download(ticker, start_date, end_date)

C:\Users\benel\AppData\Local\Temp\ipykernel_26248\155153850.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(ticker, start_date, end_date)
[*********************100%***********************]  1 of 1 completed

In [3]:
df.columns = df.columns.droplevel(1)

df.head()

Price            Close        High         Low        Open    Volume
Date
2020-01-02  151.829544  151.933525  149.664878  150.090248  22622100
2020-01-03  149.939011  151.196224  149.409661  149.655441  21116200
2020-01-06  150.326569  150.392745  147.944480  148.483292  20813700
2020-01-07  148.955902  150.931516  148.710137  150.600680  21634100
2020-01-08  151.328537  151.999686  149.305656  150.232018  27746500

In [4]:
df['Return'] = df['Close'].pct_change()

df['SMA20'] = df['Close'].rolling(20).mean()
df['SMA50'] = df['Close'].rolling(50).mean()

df['Volatility'] = df['Return'].rolling(20).std()

In [5]:
df.tail()

Price,Close,High,Low,Open,Volume,Return,SMA20,SMA50,Volatility
Date,,,,,,,,,
2025-12-23,484.691528,485.667164,482.590867,482.829824,14683600,0.003980,481.135867,496.477027,0.012476
2025-12-24,485.856323,486.991284,482.680464,483.526701,5855900,0.002403,481.684923,495.987395,0.012425
2025-12-26,485.547699,485.955885,483.805458,484.552133,8842200,-0.000635,481.794931,495.494373,0.011795
2025-12-29,484.940430,486.184888,482.033362,482.710340,10893400,-0.001251,481.550519,495.025377,0.011386
2025-12-30,485.318726,487.508953,483.347493,483.775579,13944500,0.000780,481.587355,494.524794,0.011127

In [6]:
df['Target'] = (df['Close'].shift(-1) > df['Close']).astype(int)

In [7]:
df.tail()

Price,Close,High,Low,Open,Volume,Return,SMA20,SMA50,Volatility,Target
Date,,,,,,,,,,
2025-12-23,484.691528,485.667164,482.590867,482.829824,14683600,0.003980,481.135867,496.477027,0.012476,1
2025-12-24,485.856323,486.991284,482.680464,483.526701,5855900,0.002403,481.684923,495.987395,0.012425,0
2025-12-26,485.547699,485.955885,483.805458,484.552133,8842200,-0.000635,481.794931,495.494373,0.011795,0
2025-12-29,484.940430,486.184888,482.033362,482.710340,10893400,-0.001251,481.550519,495.025377,0.011386,1
2025-12-30,485.318726,487.508953,483.347493,483.775579,13944500,0.000780,481.587355,494.524794,0.011127,0

In [8]:
import sklearn

In [ ]:
df = df.dropna(subset=['SMA50', 'Target'])

X = df[['SMA50']]

y = df['Target']

In [18]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    shuffle=False
)

In [19]:
split = int(len(df) * 0.8)

X_train = X[:split]
X_test = X[split:]

y_train = y[:split]
y_test = y[split:]

In [20]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression()

model.fit(X_train, y_train)

ValueError: Input X contains NaN.
LogisticRegression does not accept missing values encoded as NaN natively. For supervised learning, you might want to consider sklearn.ensemble.HistGradientBoostingClassifier and Regressor which accept missing values encoded as NaNs natively. Alternatively, it is possible to preprocess the data, for instance by using an imputer transformer in a pipeline or drop samples with missing values. See https://scikit-learn.org/stable/modules/impute.html You can find a list of all estimators that handle NaN values at the following page: https://scikit-learn.org/stable/modules/impute.html#estimators-that-handle-nan-values

In [59]:
predictions = model.predict(X_test)

print(predictions[:10])

AttributeError: 'LogisticRegression' object has no attribute 'coef_'

In [60]:
from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, predictions)

print("Accuracy:", accuracy)

NameError: name 'predictions' is not defined